apiVersion: apps/v1
kind: Deployment
metadata:
  name: ascii-live
  namespace: ascii-live
spec:
  selector:
    matchLabels:
      app: ascii-live
  template:
    metadata:
      labels:
        app: ascii-live
    spec:
      containers:
      - image: hugomd/ascii-live:407342dc
        name: ascii-live
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ascii-live
  namespace: ascii-live
spec:
  selector:
    app: ascii-live
  type: NodePort
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ascii-live
  namespace: ascii-live
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/preserve-host: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: ascii.live
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ascii-live
            port:
              number: 8080
  tls:
    - secretName: ascii-live-tls-prod-cert
      hosts:
        - ascii.live
